### ISSUE TITLE
Add link to docs when filesystem list is empty

### ISSUE THREAD

**Issue by seibert** [fsspec/jupyter-fsspec#14]
If there are no filesystems configured, the extension should show the user a hyperlink to the juypter-fsspec docs on how to add sources.  This is especially important because the first release won't have a UI to add a source.  (Coming later!)

**Comment by seibert** [comment]
This depends on #16

**Comment by ericsnekbytes** [comment]
This is [in progress](https://github.com/ericsnekbytes/jupyter-fsspec/tree/empty_config_hint).

**Comment by ericsnekbytes** [comment]
Yes it can!
